sudo: required
services:
  - docker

before_install:
  - docker build -t eilyart/react-test -f ./client/Docerfile.dev ./client

script:
  - docker run -e CI=true eilyart/react-test npm test

after_success:
  - docker build -t eilyart/multi-client ./client
  - docker build -t eilyart/multi-nginx ./nginx
  - docker build -t eilyart/multi-server ./server
  - docker build -t eilyart/multi-worker ./worker
  # Log in to docker CLI 
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push eilyart/multi-client
  - docker push eilyart/multi-nginx
  - docker push eilyart/multi-server
  - docker push ilyart/multi-worker
